name: 'CogniSim GH Action'
description: 'Run a Cognisim test given an api key and a test id.'
author: 'CogniSim'

# Define your inputs here.
inputs:
  test-id:
    description: 'The test id to run.'
    required: true

# Define your outputs here.
outputs:
  success:
    description: 'Whether or not the test fails.'

runs:
  using: node20
  main: dist/index.js