name: 'CogniSim GH Action'
description: 'Run a Cognisim test given an api key and a test id.'
author: 'CogniSim'

# Define your inputs here.
inputs:
  workflow-id:
    description: 'The workflow id to run.'
    required: false
  test-id:
    description: 'The test id to run.'
    required: false
  revyl-device-url:
    description: 'The Revyl device URL server to use.'
    required: false
  retries:
    description: 'The number of times to retry the test.'
    required: false
  llm_model_name:
    description: 'The LLM model name to use.'
    required: false
  multimodal:
    description: 'Whether or not run the test multimodal'
# Define your outputs here.
outputs:
  success:
    description: 'Whether or not the test fails.'
runs:
  using: node20
  main: dist/index.js
