name: 'CogniSim GH Action'
description: 'Run a Cognisim test given an api key and a test id.'
author: 'CogniSim'

# Define your inputs here.
inputs:
  workflow-id:
    description: 'The workflow id to run.'
    required: false
  test-id:
    description: 'The test id to run.'
    required: false
  revyl-device-url:
    description: 'The Revyl device URL server to use.'
    required: false
  retries:
    description: 'The number of times to retry the test.'
    required: false
  llm_model_name:
    description: 'The LLM model name to use.'
    required: false
  build-version-id:
    description:
      'Optional build version ID to use for this test execution. Overrides the
      build version attached to the test.'
    required: false
  timeout:
    description:
      'Timeout in seconds for the execution to complete. Default 3600.'
    required: false
  poll-interval:
    description:
      'Polling interval in seconds when checking execution status. Default 15.'
    required: false

# Define your outputs here.
outputs:
  success:
    description: 'Whether or not the test/workflow succeeded.'
  task_id:
    description: 'The task identifier returned by the async API.'
  execution_time:
    description: 'Total execution time reported by the platform.'
  platform:
    description: 'Execution platform (web, ios, android).'
  error_message:
    description: 'Error message if execution failed.'
  # Workflow-specific outputs
  total_tests:
    description: 'Total number of tests in the workflow.'
  completed_tests:
    description: 'Number of tests completed in the workflow.'
  passed_tests:
    description: 'Number of tests that passed in the workflow.'
  failed_tests:
    description: 'Number of tests that failed in the workflow.'
  # Test-specific outputs
  total_steps:
    description: 'Total number of steps in the test.'
  completed_steps:
    description: 'Number of steps completed in the test.'
runs:
  using: node20
  main: dist/index.js
